package com.challenge.github.core.util

class Message {
    companion object {
        const val GENERIC_ERROR_MESSAGE =
            "Aconteceu um erro inesperado. Por favor, tente novamente mais tarde."
    }
}